manifest:
  remotes:
    - name: zmkfirmware
      url-base:  https://github.com/zmkfirmware
    - name: zmk
      url-base: https://github.com/Krillleeee
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feat/pointers-move-scroll
    - name: zmk
      remote: zmk
      revision: trackpad_dev
    import: app/west.yml
  self:
    path: config
