manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/ufan
  projects:
    - name: zmk
      remote: zmk
      revision: trackpad_dev
      import: app/west.yml
  self:
    path: config
