manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/Krillleeee
  projects:
    - name: zmk-fork-clone
      remote: zmk-fork-clone
      revision: main
      import: app/west.yml
  self:
    path: config
